Lab3/Lab3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('polls.urls', namespace='polls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

Lab3/polls/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'search$', views.search, name='search'),
    url(r'^create/$', views.create, name='create'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<question_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<question_id>[0-9]+)/comments/$', views.comments, name='comments'),
]

Lab3/polls/models.py
from __future__ import unicode_literals
import datetime
from django.contrib.auth.models import User

from django.db import models
from django.utils import timezone


class Question(models.Model):
    author = models.ForeignKey(User)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text

    def __unicode__(self):
        return self.question_text

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    def __unicode__(self):
        return self.choice_text


class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(max_length=200)
    author = models.ForeignKey(User)
    create_date = models.DateTimeField('create date', default=timezone.now)

    def __str__(self):
        return self.content

    def __unicode__(self):
        return self.content

Lab3/polls/forms.py
from django.forms import ModelForm, inlineformset_factory, modelform_factory

from .models import Question, Choice, Comment


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        exclude = ['author', 'pub_date']


class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        exclude = ['votes']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

ChoiceFormSet = inlineformset_factory(Question, Choice, form=ChoiceForm, extra=3, can_delete=False)
QuestionChangeFormSet = inlineformset_factory(Question, Choice, form=QuestionForm, extra=0, can_delete=False)

Lab3/polls/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic

from .models import Question, Choice, Comment
from polls.forms import QuestionForm, ChoiceFormSet, QuestionChangeFormSet, CommentForm


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class AboutView(generic.TemplateView):
    template_name = 'polls/about.html'


class ContactView(generic.TemplateView):
    template_name = 'polls/contact.html'


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:10]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    votes = question.choice_set.aggregate(Sum('votes'))['votes__sum']
    form = CommentForm()
    return render(request, 'polls/results.html', {'question': question, 'votes': votes, 'form': form})


@login_required
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


def search(request):
    if request.GET and 'query' in request.GET:
        query = request.GET['query']
        questions = Question.objects.filter(question_text__contains=query)

        if questions.count() > 0:
            context = {'latest_question_list': questions}
        else:
            context = {'info_message': 'No matches found.'}

        return render(request, 'polls/index.html', context)
    else:
        return HttpResponseRedirect('/')


@login_required
def create(request):
    new_question = Question(author=request.user)
    if request.POST:
        form = QuestionForm(request.POST, instance=new_question)
        if form.is_valid():
            poll = form.save(commit=False)
            poll.author = request.user

            formset = ChoiceFormSet(request.POST, instance=poll)
            if formset.is_valid():
                poll.save()
                formset.save()
                return HttpResponseRedirect('/')
        else:
            formset = ChoiceFormSet(instance=new_question)
    else:
        form = QuestionForm(instance=new_question)
        formset = ChoiceFormSet(instance=new_question)

    return render(request, 'polls/create.html', {'form': form, 'formset': formset})


@login_required
def edit(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        return HttpResponseRedirect('/')

    if request.POST:
        formset = QuestionChangeFormSet(request.POST, instance=question)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))
    else:
        formset = QuestionChangeFormSet(instance=question)

    return render(request, "polls/edit.html", {'formset': formset, 'question': question})


@login_required
def comments(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.question = question
            comment.save()
    else:
        form = CommentForm()

    return redirect(reverse('polls:results', args=(question.id,)))


@login_required
def delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return HttpResponseRedirect('/')

Lab3/polls/templates/base.html
{% load bootstrap3 %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    {% bootstrap_css %}
</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'polls:index' %}">{% trans 'Home' %}</a></li>
                    <li><a href="{% url 'polls:about' %}">{% trans 'About' %}</a></li>
                    <li><a href="{% url 'polls:contact' %}">{% trans 'Contact' %}</a></li>
                </ul>
                {% block nav_user %}
                    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-right">
                            <li id="nav-username">
                                <a href="#profile">
                                    <span class="glyphicon glyphicon-user"></span> {{ user.get_username }}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'auth_logout' %}">{% trans 'Sign out' %}</a>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="{% url 'auth_login' %}">{% trans 'Log in' %}</a>
                            </li>
                            <li>
                                <a href="{% url 'registration_register' %}">{% trans 'Register' %}</a>
                            </li>
                        </ul>
                    {% endif %}
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <div id="page-footer">
        <div class="container">
            <footer>
                <hr />
                <p>&copy; Polls 2015</p>
            </footer>
        </div>
    </div>
    {% bootstrap_javascript jquery=True %}
</body>
</html>

Lab3/polls/templates/polls/about.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'About' %}{% endblock %}

{% block content %}
    <p>{% trans 'About' %}</p>
{% endblock %}

Lab3/polls/templates/polls/contact.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Contant' %}{% endblock %}

{% block content %}
    <p>{% trans 'Contant' %}</p>
{% endblock %}

Lab3/polls/templates/polls/create.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Create' %}{% endblock %}

{% block content %}
    <form method="post" action="{% url 'polls:create' %}">
        {% csrf_token %}
        {{ form|crispy }}
        {{ formset.management_form }}
        {% for choise_form in formset %}
            {{ choise_form|crispy }}
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="{% trans 'Create' %}" />
    </form>
{% endblock %}

Lab3/polls/templates/polls/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Details' %}{% endblock %}

{% block content %}
    {% if error_message %}
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>Warning!</strong> {{ error_message }}
        </div>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>{{ question.question_text }}</h4>
            </div>
            <ul class="list-group">
                {% for choice in question.choice_set.all %}
                    <li class="list-group-item">
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                    </li>
                {% endfor %}
            </ul>
            <div class="panel-footer">
                <input class="btn btn-primary" type="submit" value="Vote" />
                {% if user == question.author %}
                    <a href="{% url 'polls:edit' question.id %}" class="btn btn-info" role="button">Change</a>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock content %}

Lab3/polls/templates/polls/edit.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Edit' %}{% endblock %}

{% block content %}
    <form method="post" action="{% url 'polls:edit' question.id %}">
        {% csrf_token %}
        {{ formset.management_form|crispy }}
        {% for choise_form in formset %}
            {{ choise_form|crispy }}
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="{% trans 'Save' %}" />
    </form>
{% endblock %}

Lab3/polls/templates/polls/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Polls' %}{% endblock %}

{% block content %}
    <form method="get" action="{% url 'polls:search' %}">
        <div class="form-group">
            <input name="query" type="text" class="form-control" required placeholder="Search for...">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
        <a href="{% url 'polls:create' %}" class="btn btn-info" role="button">Create</a>
    </form>
    <hr>
    {% block results %}
        {% if latest_question_list %}
            <div class="list-group">
                {% for question in latest_question_list %}
                    <div class="list-group-item clearfix">
                        <span class="glyphicon glyphicon-question-sign"></span>
                        <span class="list-group-item-heading">
                            <a href="{% url 'polls:results' question.id %}">
                                {{ question.question_text }}
                            </a>
                        </span>
                        <span class="list-group-item-text">
                            {{ question.author }}
                            {{ question.pub_date }}
                        </span>
                        <span class="pull-right">
                            <a href="{% url 'polls:delete' question.id %}" class="btn btn-xs btn-warning">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </span>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            {% if info_message %}
                <div class="alert alert-info alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ info_message }}
                </div>
            {% else %}
                <p>{% trans 'No poslls are available.' %}</p>
            {% endif %}
        {% endif %}
    {% endblock results %}
{% endblock content %}

Lab3/polls/templates/polls/results.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load poll_extras %}

{% block title %}{% trans 'Polls' %}{% endblock %}

{% block content %}
    <h4>{{ question.question_text }}</h4>

    {% for choice in question.choice_set.all %}
        <strong>{{ choice.choice_text }}</strong>
        <span class="pull-right">{{ choice.votes }}</span>
        <div class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar"
                 aria-valuenow="{{ choice.votes|percentage:votes }}"
                 aria-valuemin="0" aria-valuemax="100"
                 style="width:{{ choice.votes|percentage:votes }}%;">
                {{ choice.votes|percentage:votes }}%
            </div>
        </div>
    {% endfor %}
    <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">{% trans 'Vote again?' %}</a>
    <hr>
    <form method="post" action="{% url 'polls:comments' question.id %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-default">Send</button>
    </form>
    <br/>
    {% for comment in question.comment_set.all %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ comment.author }}</h3>
            </div>
            <div class="panel-body">
                {{ comment.content|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
{% endblock content %}